[changelog]
header = """
# Changelog
All notable changes to this project will be documented in this file.
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = true

commit_parsers = [
  { message = "^feat", group = "Features"},
  { message = "^fix", group = "Bug Fixes"},
  { message = "^docs", group = "Documentation"},
  { message = "^style", group = "Styling"},
  { message = "^refactor", group = "Refactor"},
  { message = "^perf", group = "Performance"},
  { message = "^test", group = "Testing"},
  { message = "^chore", group = "Miscellaneous Tasks"},
  { message = "^ci", group = "CI/CD"},
  { message = "^build", group = "Build System"},
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = "v0.1.0-beta.1"
ignore_tags = ""
topo_order = false
sort_commits = "newest"
